- name: register to RedHat Network
  redhat_subscription: state=present username={{rhn_user}} \
    password={{rhn_pass}} autosubscribe=true
  ignore_errors: yes # temporary
  tags: [rhn, rhn_register]

- name: consume Subscription Red Hat Enterprise Server
  redhat_subscription: state=present username={{rhn_user}} \
    password={{rhn_pass}} pool='^(Red Hat Enterprise Server|Red Hat Satellite)'
  tags: [rhn, rhn_channel]

- name: enable repo on subscription manager
  shell: subscription-manager repos --enable rhel-7-server-rpms \
         --enable rhel-server-rhscl-7-rpms \
         --enable rhel-7-server-satellite-6.1-rpms
  tags: [rhn, rhn_enablerepo]

- name: install chrony daemon (old ntpd)
  yum: name=chrony state=latest
  register: chrony
  tags: ntp

- name: start chronyd
  service: name=chronyd state=started enabled=yes
  when: chrony|success
  tags: ntp

- name: firewalld flows opening
  shell: firewall-cmd --permanent --add-port="53/udp" --add-port="53/tcp" \
          --add-port="67/udp" --add-port="68/udp" \
          --add-port="69/udp" --add-port="80/tcp" \
          --add-port="443/tcp" --add-port="5647/tcp" \
          --add-port="8140/tcp" \
          && firewall-cmd --reload
  tags: firewalld

- name: checking SELinux status
  debug: msg="SELinux is {{ ansible_selinux.status }} with policy {{ ansible_selinux.type }}"
  tags: selinux
